/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "native.h"
#include <cassert>
#include <iostream>

int main() {
    std::cout << "hello world!" << std::endl;
    return 0;
}
